apiVersion: v1
kind: Service
metadata:
  name: {{ include "word2number.fullname" . }}
  labels:
    {{- include "word2number.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "word2number.selectorLabels" . | nindent 4 }}
