apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }} 
  namespace: "default"
  labels:
    app: {{ .Values.configmap.labelname }}
data:
  POSTGRES_DB: {{ .Values.configmap.postgresdb | quote }}
  POSTGRES_USER: {{ .Values.configmap.postgresuser | quote }}
  POSTGRES_PASSWORD: {{ .Values.configmap.postgrespassword | quote }}

