apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }} 
spec:
  accessModes:
    - {{ .Values.pvc.access }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}