apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  labels:
    app: {{ .Values.service.labelname }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.service.labelname }} 